import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Footer from "./_components/footer";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300","400","500","600","700"], // Escolha os pesos que vai usar
});


export const metadata: Metadata = {
  title: "Confeitaria",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <div className="flex flex-col  min-h-screen">
          <div className="flex-1">{children}</div>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
